# -*- coding: utf-8 -*-
"""practice_problems.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kI63EJnepkHbfLWLZ7esIhOkTTZb0_AD
"""

"""1. User will input (3ages).Find the oldest one"""
def ages(age1, age2, age3):
  if age1 > age2 and age1 > age3:
    return age1
  if age2 > age1 and age2 > age3:
    return age2
  else:
    return age3

ages(10,30,25)

"""1. User will input (3ages).Find the oldest one"""

ages = {
    "age1": int(input("Enter first age: ")),
    "age2": int(input("Enter second age: ")),
    "age3": int(input("Enter third age: "))
}

def find_oldest(age_dict):
  age1 = ages["age1"]
  age2 = ages["age2"]
  age3 = ages["age3"]
  if age1 >= age2 and age1 >= age3:
    return age1
  if age2 >= age1 and age2 >= age3:
    return age2
  else:
    return age3
find_oldest(ages)

"""1. User will input (3ages).Find the oldest one"""
ages = {
    "age1": int(input("Enter first age: ")),
    "age2": int(input("Enter second age: ")),
    "age3": int(input("Enter third age: "))
}
def find_oldest(age_dict):
  return max(ages.values())

find_oldest(ages)

"""2. Write a program that will convert celsius value to fahrenheit"""

num=int(input("Enter the celsius value: "))
def convert_to_fahrenheit(num):
  return (num*1.8)+32

convert_to_fahrenheit(num)

"""3. User will input (2numbers).Write a program to swap the numbers"""
a=int(input("Enter first number: "))
b=int(input("Enter second number: "))
def swap(a,b):
  a,b=b,a
  return a,b
swap(a,b)

"""3. User will input (2numbers).Write a program to swap the numbers"""

L = []

def swap(list):
  if len(L) < 2:
    print("List must contain at least two numbers to swap.")
    return L

  L[0], L[1] = L[1], L[0]
  return L

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

L.append(a)
L.append(b)

print(f"Original numbers: {L}")
swapped_numbers = swap(L)
print(f"Swapped numbers: {swapped_numbers}")

"""3. User will input (2numbers).Write a program to swap the numbers"""

def swap(a,b):
  temp = a
  a = b
  b = temp
  return a, b

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

print(f"Original numbers: {a}, {b}")
swapped_numbers = swap(a,b)
print(f"Swapped numbers: {swapped_numbers}")

"""4. Write a program that will give you the sum of 3 digits"""
def sum_of_three_num(a, b, c):
  return a+b+c
a= int(input("Enter first number: "))
b= int(input("Enter second number: "))
c= int(input("Enter third number: "))

print(sum_of_three_num(a,b,c))

"""4. Write a program that will give you the sum of 3 digits"""
L = []

a= int(input("Enter first number: "))
b= int(input("Enter second number: "))
c= int(input("Enter third number: "))

L.append(a)
L.append(b)
L.append(a)

def sum_of_three_number(list):
  for i in range(len(L)):
    return sum(L)


print(L)
print(sum_of_three_number(L))

"""4. Write a program that will give you the sum of 3 digits"""

numbers = list(map(int, input("Numbers space se likho: ").split()))
print(numbers)

def sum_of_numbers(numbers):
  return sum(numbers)

print(sum_of_numbers(numbers))

"""5. Write a program that will reverse a four digit number.Also it checks whether the reverse is true."""
a = input("Enter Number: ")
print(a)

def check(number):
  return number[::-1]

result = check(a)
print(result)

if a==result:
  print("True")
else:
  print("False")

"""5. Write a program that will reverse a four digit number.Also it checks whether the reverse is true."""

a=input("Enter number: ")

def number_reverse(num):
  rev = ""
  for char in num:
    rev = char + rev
  return rev

rev = number_reverse(a)
print(rev)

if a == rev:
  print("True Palindrome")
else:
  print("False Palindrome")

"""6. Write a program that will tell whether the number entered by the user is odd or even."""

def check_number(num):
  if num < 2:
    return num
  if num %2==0:
    return "even"
  else:
    return "odd"

check_number(4)

"""6. Write a program that will tell whether the number entered by the user is odd or even."""

numbers = list(map(int, input("Enter Numbers: ").split()))
print(numbers)

for num in numbers:
  if num < 2:
    print("Can't do it: ", num)
  if num %2 == 0:
    print("Even Number")
  elif num < 2:
    pass
  else:
    print("Odd Number")

"""6. Write a program that will tell whether the number entered by the user is odd or even."""

numbers = list(map(int, input("Enter Numbers: ").split()))
print("Input Numbers:", numbers)

result = []

for num in numbers:
    if num < 2:
        result.append(f"{num}: Can't do it")
    elif num % 2 == 0:
        result.append(f"{num}: Even")
    else:
        result.append(f"{num}: Odd")

print("Results:", result)

"""7. Write a program that will tell whether the given year is a leap year or not."""

year = int(input("Enter a year: "))

if year % 400 == 0:
    print(f"{year} is a Leap Year")
elif year % 100 == 0:
    print(f"{year} is NOT a Leap Year")
elif year % 4 == 0:
    print(f"{year} is a Leap Year")
else:
    print(f"{year} is NOT a Leap Year")

"""8. Write a program to find the euclidean distance between two coordinates."""

x1 = int(input("Enter x1: "))
y1 = int(input("Enter y1: "))
x2 = int(input("Enter x2: "))
y2 = int(input("Enter y2: "))

def eucledian_dist(x1, x2, x3, x4):
  return ((x2-x1)**2 + (y2-y1)**2)**0.5

print(eucledian_dist(x1, x2, y1, y2))

"""8. Write a program to find the euclidean distance between two coordinates."""

import math

x1 = int(input("Enter x1: "))
y1 = int(input("Enter y1: "))
x2 = int(input("Enter x2: "))
y2 = int(input("Enter y2: "))

distance = math.sqrt(sum([(x2 - x1)**2, (y2 - y1)**2]))
print(distance)

"""8. Write a program to find the euclidean distance between two coordinates."""

import math

a = list(map(int, input("Enter numbers for point 1: ").split()))
b = list(map(int, input("Enter numbers for point 2: ").split()))

print("Point 1:", a)
print("Point 2:", b)

distance = math.sqrt(sum((y - x)**2 for x, y in zip(a, b)))

print("Euclidean Distance:", distance)

"""9. Write a program that take a user inputr of three angles and will find out whether it can form a triangle or not."""

import math

a = int(input("Enter Angle: "))
b = int(input("Enter Angle: "))
c = int(input("Enter Angle: "))

def triangle(a, b, c):
  if sum([a, b, c]) == 180:
    return "It is a Triangle"
  else:
    return "It is not a Triangle"

triangle(a, b, c)

"""9. Write a program that take a user inputr of three angles and will find out whether it can form a triangle or not."""

num = list(map(int, input("Enter angles: ").split()))
print(num)

def triangle(list):
  if sum(list) > 180:
    return "It is not Possible"
  elif sum(list) == 180:
    return "It is a Triangle"
  else:
    return "It is not a Triangle"

print(triangle(num))
print(sum(num))

"""9. Write a program that take a user inputr of three angles and will find out whether it can form a triangle or not."""

import math

L = []

a = int(input("Enter Angle: "))
b = int(input("Enter Angle: "))
c = int(input("Enter Angle: "))

L.append(a)
L.append(b)
L.append(c)

print(L)

def triangle(list):
  if sum(list) > 180:
    return "It is not Possible"
  elif sum(list) == 180:
    return "It is a Triangle"
  else:
    return "It is not a Triangle"

result = triangle(L)
print(f"Sum of angles = {sum(L)} → {result}")

"""10. Write a program that will take user input of cost price and selling price and determines whether its a loss or a profit"""


cost_price = int(input("Enter Cost Price: "))
selling_price = int(input("Enter Selling Price: "))

def profit_loss(cost, sell):
  if cost < 0 and sell < 0:
    return "Not Possible"
  if cost > sell:
    return ("You got", f'{sell-cost}', "You Sold the Product in Loss")
  else:
    return ("You earned", f'{sell-cost}', "You Sold the Product in Profit")

profit_loss(cost_price, selling_price)

#Max Number

L = list(map(int, input("Enter numbers: ").split()))

max_num = L[0]

for num in L:
    if num > max_num:
        max_num = num

print("Max number:", max_num)

"""11. Write a program to find the simple interest when the value of principle,rate of interest and time period is given."""

principal_value = int(input("Enter Principal Value: "))
rate_of_interest = float(input("Enter Rate of Interest: "))
time = int(input("Enter Time: "))

def simple_ineterest(principal, interest, time):
  return (principal*interest*time)/100

print(simple_ineterest(principal_value, rate_of_interest, time))

"""12. Write a program to find the volume of the cylinder. Also find the cost when ,when the cost of 1litre milk is 40Rs."""

radius = float(input("Enter Radius in cm: "))
height = float(input("Enter Height in cm: "))

def volume_of_cylinder(radius, height):
  return (3.142*radius*height)

litre = volume_of_cylinder(radius, height)
print("Volume of cylinder is: ", litre)

def cost_of_milk(litre, cost):
  return (litre/1000)*cost

price = cost_of_milk(litre, 20)
print("Price of milk is PKR/Litre2: ", price)

"""13. Write  a program that will tell whether the given number is divisible by 3 & 6."""

def check(a):
  if a%3==0 & a%6==0:
    return "Number is Divisible by 3 & 6"

check(9)

"""13. Write  a program that will tell whether the given number is divisible by 3 & 6."""

divisible_by_3_and_6 = lambda x: "Divisible by 3 and 6" if x % 3 == 0 and x % 6 == 0 else "Not divisible by 3 and 6"

print(divisible_by_3_and_6(9))

"""14. Angle between hour and minute hand

link: https://www.geeksforgeeks.org/problems/angle-between-hour-and-minute-hand0545/1?page=2&sortBy=submissions&category%5B%5D=Mathematical"""

time = input("Enter Time in format HH:MM ")
list = []

list.append(int(time[:2]))
list.append(int(time[3:]))

def angle(hour, minute):
  return (hour*30) - (minute*0.5)

print(angle(list[0], list[1]))

"""15. https://www.geeksforgeeks.org/problems/overlapping-rectangles1924/1?page=3&sortBy=submissions&category%5B%5D=Mathematical"""

L1 = (0,1)
L2 = (10,0)
L3 = (5,5)
L4 = (15,0)

def overlap(L1, L2, L3, L4):
  if (L2[0] <= L3[0] or L1[0] >= L4[0] or L2[1] <= L3[1] or L1[1] >= L4[1]):
    return "Not Overlap"
  else:
    return "Overlap"

print(overlap(L1, L2, L3, L4))

"""15. https://www.geeksforgeeks.org/problems/overlapping-rectangles1924/1?page=3&sortBy=submissions&category%5B%5D=Mathematical"""

L1 = (0, 2)
L2 = (1, 1)
L3 = (-2, 0)
L4 = (0, 3)

def overlap(L1, L2, L3, L4):
    if (L2[0] <= L3[0] or
        L1[0] >= L4[0] or
        L2[1] <= L3[1] or
        L1[1] >= L4[1]):
        return "Not Overlap"
    else:
        return "Overlap"

print(overlap(L1, L2, L3, L4))

"""15. https://www.geeksforgeeks.org/problems/overlapping-rectangles1924/1?page=3&sortBy=submissions&category%5B%5D=Mathematical"""

L1 = (0, 2)
L2 = (1, 1)
L3 = (-2, 0)
L4 = (0, 3)

overlap = lambda L1, L2, L3, L4 : "Not Overlap" if (L2[0] <= L3[0] or L1[0] >= L4[0] or L2[1] <= L3[1] or L1[1] >= L4[1]) else "Overlap"
print(overlap(L1,L2, L3, L4))

"""16. Write a program that will determine weather when the value of temperature and humidity is provided by the user.
TEMPERATURE(C)      HUMIDITY(%)      WEATHER


      >= 30                             >=90                Hot and Humid

      >= 30                             < 90                 Hot

      <30                                >= 90               Cool and Humid

      <30                                 <90                 Cool"""

humi = int(input("Enter Humidity: "))
temp = int(input("Enter Temperature: "))

def weather(humidity, temp):
  if temp >= 30 and humidity >=90:
    print("Hot and Humid")
  if temp >=30 and humidity < 90:
    print("Hot")
  if temp < 30 and humidity >= 90:
    print("Humid")
  if temp < 30 and humidity < 90:
    print("Cool")

weather(humi, temp)

"""Write a program that will determine weather when the value of temperature and humidity is provided by the user.
TEMPERATURE(C)      HUMIDITY(%)      WEATHER


      >= 30                             >=90                Hot and Humid

      >= 30                             < 90                 Hot

      <30                                >= 90               Cool and Humid

      <30                                 <90                 Cool"""

humi = int(input("Enter Humidity: "))
temp = int(input("Enter Temperature: "))

weather = lambda humi, temp: "Hot and Humid" if temp >= 30 and humi >=90 else "Hot" if temp >=30 and humi < 90 else "Humid" if temp < 30 and humi >= 90 else "Cool"
print(weather(humi, temp))

"""17. Write a program that will take three digits from the user and add the square of each digit."""


L = []
a = int(input("Enter Number: "))
b = int(input("Enter Number: "))
c = int(input("Enter Number: "))

L.append(a)
L.append(b)
L.append(c)

def square(list):
  for i in list:
    print (i**2)

square(L)

"""### Pattern Problems"""

print("*"*5)

for i in range(5):
  print("*")

for i in range(5):
  print("*", end="")

for i in range(6):
  print("*", end=" ")

for i in range(10):
  print("1")

for i in range(10):
  print("1", end="")

for i in range(5):
  for j in range(5):
    print("*", end="")

for i in range(5):
  for j in range(5):
    print("*", end="")
  print()

for i in range(5):
  for j in range(5):
    print("*", end=" ")
  print()

for i in range(5):
  for j in range(i+1):
    print("*", end="")
  print()

# Increasing Triangle of *

for i in range(5):
  for j in range(i+1):
    print("*", end=" ")
  print()

# Decreasing Triangle of *

n=6
for i in range(n):
  for j in range(i, n):
    print("*", end=" ")
  print()

#Decreasing Triangle of Spaces + Increasing Triangle of *

n=6
for i in range(n):

  for j in range(i, n):
    print(" ", end=" ")

  for j in range(i+1):
    print("*", end=" ")
  print()

#Increasing Triangle of Spaces + Decreasing Triangle of *

n=6
for i in range(n):

  for j in range(i+1):
    print(" ", end=" ")

  for j in range(i, n):
    print("*", end=" ")

  print()

#Decreasing Triangle of Spaces + Increasing Triangle of * + Increasing Triangle of *

n=6
for i in range(n):

  for j in range(i, n):
    print(" ", end=" ")

  for j in range(i+1):
    print("*", end=" ")

  for j in range(i+1):
    print("*", end=" ")

  print()

#Increasing Triangle of Spaces + Deccreasing Triangle of * + Decreasing Triangle of *

n=6
for i in range(n):

  for j in range(i, n):
    print(" ", end=" ")

  for j in range(i):
    print("*", end=" ")

  for j in range(i+1):
    print("*", end=" ")

  print()

#Deccreasing Triangle of Spaces + Inccreasing Triangle of * + Increasing Triangle of *

n=6
for i in range(n):

  for j in range(i + 1):
    print(" ", end=" ")

  for j in range(i, n):
    print("*", end=" ")

  for j in range(i, n):
    print("*", end=" ")

  print()

#Decccreasing Triangle of Spaces + Increasing Triangle of * + Increasing Triangle of *

n=6
for i in range(n):

  for j in range(i + 1):
    print(" ", end=" ")

  for j in range(i, n):
    print("*", end=" ")

  for j in range(i, n):
    print("*", end=" ")

  print()

#Decccreasing Triangle of Spaces + Increasing Triangle of * + Increasing Triangle of *

n=6
for i in range(n):

  for j in range(i + 1):
    print(" ", end=" ")

  for j in range(i, n-1):
    print("*", end=" ")

  for j in range(i, n):
    print("*", end=" ")

  print()

#Increasing Triangle of Spaces + Deccreasing Triangle of * + Decreasing Triangle of *

n=6
for i in range(n):

  for j in range(i, n):
    print(" ", end=" ")

  for j in range(i):
    print("*", end=" ")

  for j in range(i+1):
    print("*", end=" ")

  print()

#Decccreasing Triangle of Spaces + Increasing Triangle of * + Increasing Triangle of *

n=6
for i in range(n):

  for j in range(i + 1):
    print(" ", end=" ")

  for j in range(i, n-1):
    print("*", end=" ")

  for j in range(i, n):
    print("*", end=" ")

  print()